### ISSUE TITLE
[Request] Way to tell the http connection was closed

### ISSUE THREAD

**Issue by vespakoen** [cesanta/mongoose-iot#110]
Hey,

I am keeping a connection open, and use setInterval to send data to a connected client.
When the client disconnects, I would like to receive an event so I can stop the timer appropriately.

Perhaps there is already something like this built in?

**Comment by cpq** [comment]
I guess a `onclose` event makes sense here. Could you show your code, and anticipated `onclose` handling, please?

**Comment by alashkin** [comment]
Added `on` method and `close` event.
See here for details: https://github.com/cesanta/mongoose-iot/blob/master/docs/javascript-api/http.md
