### ISSUE TITLE
File.read() data amount parameter?

### ISSUE THREAD

**Issue by carterw** [cesanta/mongoose-iot#122]
In the API docs we see;
file_obj.read() -> string: Read portion of data from an opened file stream

How to specify the amount of file data to read in? Is there an undocumented argument there? Also Its very likely that you will want to read in subsequent parts of the file so there should be an optional offset argument as well?

file_obj.read(offSet, nBytes) ??
or
file_obj.read( { offSet: off, nBytes: nb} ) ??

**Comment by alashkin** [comment]
Sorry, but the portion size is platform dependent and cannot be changed via File API.
I put this information into the doc, to `le_obj.read() -> string` description:
https://github.com/cesanta/mongoose-iot/blob/master/docs/javascript-api/file.md
