### ISSUE TITLE
Problem With Boot Loop ESP12E

### ISSUE THREAD

**Issue by prinzipx** [cesanta/mongoose-iot#125]
Hello,
i'm really new to this, so please excuse my poor english and my questions.
I have a ESP8266-12E chip and the power Supply is via 3,3 V Raspberry Pi.
After Installation and after the commands "`Wifi.setup('wlanname', 'wlanpw')`" and "`registerDevice()`", the ESP reboots every 10 Seconds.
I have attached some screenshots from the boot-process, is it a problem from the Power supply (because of the "` ets Jan  8 2013,rst cause:2, boot mode:(3,7)`")?
Can someone help me please? Thanks a lot.

Kind regards,
David

![image](https://cloud.githubusercontent.com/assets/6715841/14940954/61fa0a12-0f8b-11e6-854b-694daca9b518.png)

![image](https://cloud.githubusercontent.com/assets/6715841/14940950/59113178-0f8b-11e6-8b8d-c5e0e5ee7809.png)

**Comment by prinzipx** [comment]
Hello again,
i forgot that i was not able to flash the chip via the FnC so i flashed it via "`ESP FLASH DOWNLOAD TOOL`".
I dont know if this information is relevant.

![image](https://cloud.githubusercontent.com/assets/6715841/14940965/e4d1fe22-0f8b-11e6-9bc0-1baf15ffad9a.png)

**Comment by prinzipx** [comment]
Hallo,

now (after breakfast ;-) ) the ESP have stopped rebooting. Here a new Screenshot.
![image](https://cloud.githubusercontent.com/assets/6715841/14941241/d3659802-0f94-11e6-97dc-25c1c672df72.png)
I'm really sorry to post so much here, please close the issue because i think its a problem of me and not of mongoose iot :-)

**Comment by alashkin** [comment]
Hi,
```
After Installation and after the commands "Wifi.setup('wlanname', 'wlanpw')" and "registerDevice()", the ESP reboots every 10 Seconds.
```

Looks like, that ESP was flashed with wrong flash-size parameters
(see here for details: https://github.com/cesanta/mongoose-iot/blob/master/docs/faq/intro.md#q-i-flashed-esp-module-with-mongoose-iot-it-is-successfully-booted-and-joined-wifi-but-after-reset-the-device-reboots-over-and-over)

But anyway, as I understand, FNC doesn't work for you.
You use Windows 10, right?

**Comment by alashkin** [comment]
Hello,
How it is going with this issue?

**Comment by mmikulicic** [comment]
we recently fixe an issue with saving config files that caused a crash loop also after saving wifi config.
it might be related

**Comment by alashkin** [comment]
@prinzipx 
Ok, I'm closing this issue, feel free to reopen
