### ISSUE TITLE
Wifi.ip(1) problem

### ISSUE THREAD

**Issue by apmascalabs** [cesanta/mongoose-iot#126]
Hi, when I try to use 'Wifi.ip(1)' to see the IP of the AP like described in API reference, return me the same IP of the 'Wifi.ip()'. 
I've tried with WIFI disabled and 'Wifi.ip()' return me 'undefined'(of course), but also with 'Wifi.ip(1)' return me 'undefined'.
If I enable WIFI and keep enable AP with the two command I obtain the same IP given me from my WIFI.
Is it a bug?
thanks, Andrea

**Comment by apmascalabs** [comment]
Hi, have you seen something about?

**Comment by alashkin** [comment]
Fixed in https://github.com/cesanta/mongoose-iot/commit/6a80905a09811c8acf0df9c939ab67d376862586
