### ISSUE TITLE
make.sh in tools does not work on windows

### ISSUE THREAD

**Issue by tomaszchacuk** [cesanta/mongoose-iot#127]
Cannot get windows build working : 

`$ ./make.sh
make: Entering directory `/cesanta/v7'
make: Nothing to be done for `v7.c'.
make: Leaving directory `/cesanta/v7'
make: Entering directory `/cesanta/mongoose'
make: Nothing to be done for `mongoose.c'.
make: Nothing to be done for `mongoose.h'.
make: Leaving directory `/cesanta/mongoose'
  MKDIR firmware
  MKDIR /cesanta/fw/platforms/esp8266/.build
make[1]: Warning: File `/cesanta/fw/platforms/esp8266/.build' has modification time 2.2 s in the future
CC esptool2.c
gcc -O2 -Wall -c esptool2.c -o /cesanta/fw/platforms/esp8266/.build/esptool2.o
CC esptool2_elf.c
gcc -O2 -Wall -c esptool2_elf.c -o /cesanta/fw/platforms/esp8266/.build/esptool2_elf.o
LD /cesanta/fw/platforms/esp8266/.build/esptool2
gcc -o /cesanta/fw/platforms/esp8266/.build/esptool2 /cesanta/fw/platforms/esp8266/.build/esptool2.o /cesanta/fw/platforms/esp8266/.build/esptool2_elf.o
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
CC rboot-stage2a.c
LD /cesanta/fw/platforms/esp8266/.build/rboot-stage2a.elf
E2 /cesanta/fw/platforms/esp8266/.build/rboot-hex2a.h
CC rboot.c
LD /cesanta/fw/platforms/esp8266/.build/rboot.elf
E2 /cesanta/fw/platforms/esp8266/.build/rboot.bin
  GEN   ../../../fw/platforms/esp8266/ld/fw.ld (0xcaff0 @ 0x40211010) -> /cesanta/fw/platforms/esp8266/.build/0x11000.ld  GEN   /cesanta/fw/platforms/esp8266/.build/sys_config.c
make -C ../../../fw/platforms/posix V7_FEATURES='-DV7_ENABLE__File__require=1 -DV7_BUILD_PROFILE=1 -DV7_ENABLE_FILE -DV7_DISABLE_AST_TAG_NAMES -DV7_ENABLE__Math -DV7_ENABLE__Math__max -DV7_ENABLE__Math__min -DV7_ENABLE__Math__random -DV7_ENABLE__Math__round -DV7_ENABLE__Function__bind -DV7_ENABLE__Function__call -DV7_ENABLE__File__list=1 -DV7_ENABLE__Memory__stats -DV7_ENABLE__StackTrace=0 -DV7_ENABLE__Object__getPrototypeOf -DV7_ENABLE__Object__isPrototypeOf -DV7_ENABLE__Object__keys -DV7_ENABLE__Object__isExtensible -DV7_EXPOSE_PRIVATE -DV7_ENABLE_ENTITY_IDS  -DV7_MAIN' BIN_DIR=/cesanta/fw/platforms/esp8266/.build/posix_sjs_bin BUILD_DIR=/cesanta/fw/platforms/esp8266/.build/posix_sjs_build CFLAGS_EXTRA='-DV7_FREEZE'
make[1]: Entering directory `/cesanta/fw/platforms/posix'
  MKDIR /cesanta/fw/platforms/esp8266/.build/posix_sjs_bin
  MKDIR /cesanta/fw/platforms/esp8266/.build/posix_sjs_build
make[2]: Entering directory `/cesanta/v7'
make[2]: Nothing to be done for `v7.c'.
make[2]: Leaving directory `/cesanta/v7'
  GEN   /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sys_config.c
  CC    fw.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/fw.o
  CC    lnx_adc.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/lnx_adc.o
  CC    lnx_debug.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/lnx_debug.o
  CC    lnx_gpio.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/lnx_gpio.o
  CC    lnx_i2c.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/lnx_i2c.o
  CC    lnx_pwm.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/lnx_pwm.o
  CC    lnx_spi.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/lnx_spi.o
  CC    lnx_wifi.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/lnx_wifi.o
  CC    main.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/main.o
  CC    posix_hal.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/posix_hal.o
  CC    posix_uart.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/posix_uart.o
  CC    ../../../v7/v7.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/v7.o
  CC    ../../src/sj_v7_ext.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_v7_ext.o
  CC    ../../../mongoose/mongoose.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/mongoose.o
  CC    ../../src/sj_spi_js.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_spi_js.o
  CC    ../../src/sj_mongoose.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_mongoose.o
  CC    ../../src/sj_mongoose_ws_client.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_mongoose_ws_client.o
  CC    ../../src/sj_mqtt.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_mqtt.o
  CC    ../../src/sj_gpio_js.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_gpio_js.o
  CC    ../../src/sj_adc_js.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_adc_js.o
  CC    ../../src/sj_prompt.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_prompt.o
  CC    ../../src/sj_timers.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_timers.o
  CC    ../../src/sj_timers_mongoose.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_timers_mongoose.o
  CC    ../../src/sj_uart.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_uart.o
  CC    ../../src/sj_http.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_http.o
  CC    ../../src/sj_debug_js.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_debug_js.o
  CC    ../../src/sj_pwm_js.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_pwm_js.o
  CC    ../../src/sj_wifi_js.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_wifi_js.o
  CC    ../../src/clubby_proto.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/clubby_proto.o
  CC    ../../../common/ubjserializer.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/ubjserializer.o
  CC    ../../src/sj_clubby.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_clubby.o
  CC    ../../src/sj_clubby_js.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_clubby_js.o
  CC    ../../src/sj_common.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_common.o
  CC    ../../src/sj_config.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_config.o
  CC    ../../src/device_config.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/device_config.o
  CC    /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sys_config.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sys_config.o
  CC    ../../src/sj_udptcp.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_udptcp.o
  CC    ../../src/sj_utils.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_utils.o
  CC    ../../src/sj_console.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/sj_console.o
  CC    ../../../krypton/krypton.c -> /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/krypton.o
  GEN   /cesanta/fw/platforms/esp8266/.build/posix_sjs_build/build_info.c
: No such file or directory
make[1]: *** [/cesanta/fw/platforms/esp8266/.build/posix_sjs_build/build_info.c] Error 127
make[1]: Leaving directory `/cesanta/fw/platforms/posix'
make: *** [/cesanta/fw/platforms/esp8266/.build/posix_sjs_bin/fw] Error 2`

**Comment by alashkin** [comment]
The problem was in line endings.
Repo must be checked out with LF, while git for windows, by default, uses CRLF.
I added `.gitattributes` to the repo in b26c1ba43d93b449319e9af05130997ccf7029d8, and now it should be ok.
PS: i don't know how it works on Windows, so, may be the simplest way to apply this fix is to remove folder with cloned repo from disk and pull it again.
