### ISSUE TITLE
FNC not working with current FW

### ISSUE THREAD

**Issue by carterw** [cesanta/mongoose-iot#134]
I built a new firmware zip file. Unfortunately the FNC app refuses to flash it, it reports an error;
INVALID_ARGUMENT: part boot has no address specified

I am using FNC 0.8.6 which is the version you published in late April;
https://github.com/cesanta/fnc/releases

It does still work with FW zip files built a few weeks ago.

**Comment by mmikulicic** [comment]
could you please try to see if the latest FNC build works for you ?

you can run it with the `--advanced` flag to get the good old console UI if you don't like the new wizard.

**Comment by rojer** [comment]
yes, master requires new FNC build. we'll release it soon.
