### ISSUE TITLE
Error when registering a new device

### ISSUE THREAD

**Issue by okeser** [cesanta/mongoose-iot#137]
@rojer, @mmikulicic : I get the error in the attached screenshot when registering a device which already has an ID in the cloud. 

![screen shot 2016-06-29 at 10 01 25](https://cloud.githubusercontent.com/assets/13334697/16446662/9ed1b6f0-3de0-11e6-9fa7-c184896b260c.png)

**Comment by cpq** [comment]
Closing as obsolete. Thanks Omer!
