### ISSUE TITLE
Device status

### ISSUE THREAD

**Issue by okeser** [cesanta/mongoose-iot#138]
It is not easy to understand if a device is powered up and online or offline. The status column in the devices section reports "active" although device is currently not powered. Would be good to have an online/offline status. 

Also, when a device is not "online", My Switch in the mobile app hangs. 

cc: @rojer @mmikulicic 

![screen shot 2016-06-29 at 11 52 21](https://cloud.githubusercontent.com/assets/13334697/16449608/5e960a36-3df0-11e6-8a2b-412605ec51d3.png)

**Comment by cpq** [comment]
Closing as obsolete - thanks Omer!
