### ISSUE TITLE
mongoose IDE: Links don't work in API page

### ISSUE THREAD

**Issue by wallaroo** [cesanta/mongoose-iot#142]
in the api page (https://mongoose-iot.com/profile/api/) of the Mongoose IDE links to resources don't work.
Tested in chrome and firefox.

error in console:
Error: Could not resolve 'main.project.api' from state

**Comment by mmikulicic** [comment]
Could you please try https://mongoose-iot.com/profile/api// ?

How did you get the https://mongoose-iot.com/profile/api/ link ? The nav bar points to the former.

**Comment by wallaroo** [comment]
hi!
same result with https://mongoose-iot.com/profile/api//:
the page remains on /v1/Account api detail.
and for each click on other api the following error is thrown:
`vendor-c16bc78355.js:32 Error: Could not resolve 'main.project.api' from state 'main.profile.api'
    at Object.C.transitionTo (vendor-c16bc78355.js:57)
    at Object.C.go (vendor-c16bc78355.js:57)
    at vendor-c16bc78355.js:57
    at vendor-c16bc78355.js:33
    at o (vendor-c16bc78355.js:31)
    at vendor-c16bc78355.js:31`

PS.
maybe i did a bad copy-paste for the missing '/'

**Comment by mmikulicic** [comment]
yes the direct link is broken. 
can you access the API page if you click directly on the API icon on the left navigation bar ?

![image](https://cloud.githubusercontent.com/assets/52673/16911927/a04cd536-4ce1-11e6-84d3-2ef6d7ae17e8.png)

**Comment by wallaroo** [comment]
this is the test case:
1) go to https://mongoose-iot.com/
2) signin with github
3)click on api button at the left navbar (that of your image)
4) click on "CreateUser" (or whatever other api link)
result:
the page remain on initial /v1/Account api detail and the following javascript error is thrown:
`vendor-c16bc78355.js:32 Error: Could not resolve 'main.project.api' from state 'main.profile.api' at Object.C.transitionTo (vendor-c16bc78355.js:57) at Object.C.go (vendor-c16bc78355.js:57) at vendor-c16bc78355.js:57 at vendor-c16bc78355.js:33 at o (vendor-c16bc78355.js:31) at vendor-c16bc78355.js:31`

**Comment by mmikulicic** [comment]
ah, sorry; now it's clear; fixing

**Comment by wallaroo** [comment]
now all works well
