### ISSUE TITLE
link to website documentation broken

### ISSUE THREAD

**Issue by robertoostenveld** [cesanta/mongoose-iot#155]
The description of the repository (at the top of the github page) includes a link to https://docs.cesanta.com/mongoose-iot/latest/, but that returns

> Not Found
> The requested URL /mongoose-iot/latest/ was not found on this server. 

The URL https://docs.cesanta.com/mongoose-iot/ does work.

**Comment by cpq** [comment]
Thanks for reporting.
I've put a redirect to https://mongoose-iot.com/docs/#/overview/
