### ISSUE TITLE
CoAP memory leak

### ISSUE THREAD

**Issue by iliapenev** [cesanta/mongoose-iot#160]
There is memory leak, when sending CoAP messages.
Demo code could be found here:
https://gist.github.com/anonymous/61d7360c0a27eb2c4922b50ffb2be1ca
It's based on c_hello project.

```
coap_send_message      50129 Sending 1257
umm_oom_cb             50100 Failed to allocate 34
coap_send_message       4440 Sending 1258
umm_oom_cb 46619 Failed to allocate 16
```

When "Failed to allocate" appears, messages are recieved without CoAP options.
Possibly problem is in handling CoAP options.
Wireshark dump: https://drive.google.com/file/d/0B4Kd4pQQfRXeYTNDbkYyMDIwT3M/view?usp=sharing

**Comment by alashkin** [comment]
@iliapenev 
As far as I can see `mg_coap_free_options` is missed after `	mg_coap_send_message(coap_connection, &msg);`

`mg_coap_add_option` allocates options by using `alloc()`; Mongoose doesn't automatically free options  to allow resend the same message if timeout expired (UDP :( )

**Comment by iliapenev** [comment]
Sorry, I missed that. 
Resend should be handled by user, as I understand?

**Comment by alashkin** [comment]
>Resend should be handled by user, as I understand?

Yes :(

**Comment by alashkin** [comment]
Anyway, I'll update doc

**Comment by iliapenev** [comment]
Sorry for inconvenience. 
Closing issue.

**Comment by alashkin** [comment]
No worries! Thank you for feedback, I've updated doc
