### ISSUE TITLE
ESP8266 MD5

### ISSUE THREAD

**Issue by iliapenev** [cesanta/mongoose-iot#164]
In my project I'm using cs_md5() function.
Compile gives error:
```
/app/.build/mongoose-iot.a(mongoose.o):(.text.cs_md5+0x0): undefined reference to `MD5_Init'
/app/.build/mongoose-iot.a(mongoose.o):(.text.cs_md5+0x4): undefined reference to `MD5_Update'
/app/.build/mongoose-iot.a(mongoose.o):(.text.cs_md5+0x8): undefined reference to `MD5_Final'
/app/.build/mongoose-iot.a(mongoose.o): In function `cs_md5':
/mongoose-iot/mongoose/mongoose.c:12187: undefined reference to `MD5_Init'
/mongoose-iot/mongoose/mongoose.c:12187: undefined reference to `MD5_Update'
/mongoose-iot/mongoose/mongoose.c:12187: undefined reference to `MD5_Final'
```
Removing -DDISABLE_MD5 fixs problem.
https://github.com/cesanta/mongoose-iot/blob/master/fw/platforms/esp8266/Makefile.build#L207

**Comment by rojer** [comment]
there is an MD5 implementation in ROM, we use it for SSL.
https://github.com/cesanta/mongoose-iot/blob/master/common/platforms/esp8266/esp_crypto.c

**Comment by iliapenev** [comment]
@rojer 
problem still stays. 
See example. Directly cs_md5 is not used. 
https://gist.github.com/anonymous/a605d995ab9feee80a2142019a42addf
