### ISSUE TITLE
JavaScript API not linked in?

### ISSUE THREAD

**Issue by carterw** [cesanta/mongoose-iot#169]
Trying your new build mechanism today, my miot.yml file has this;

build_vars:
    MG_ENABLE_JS: 1
    MG_ENABLE_FILESYSTEM_SERVICE: 1

... and I put an app.js file into the ./fs directory with one line in it;

$ cat fs/app.js
Wifi.status()

I built and flashed the firmware, upon reset I see this printed to the console;
{"stack":"    at app.js:3\n    at cfunc_0x4023a738\n    at sys_init.js:14","message":"[Wifi] is not defined"}

**Comment by cpq** [comment]
We are refactoring JS support, and expect it to be more or less functional by the end of Jan.
At the moment, initial support is demonstrated at https://github.com/cesanta/mongoose-iot/tree/master/fw/examples/mjs_hello

The JS engine is at https://github.com/cesanta/mjs
