### ISSUE TITLE
Complete API docs?

### ISSUE THREAD

**Issue by mark-hahn** [cesanta/mongoose-iot#174]
I read the api docs on the mongoose-iot website and I was disappointed at the small size of the api.  In particular the lack of I2C.  I had given up on mongoose until I recently ran into the i2c code example here.  Is there a complete api doc somewhere?

**Comment by cpq** [comment]
The very authoritative source is header files, https://github.com/cesanta/mongoose-iot/tree/master/fw/src
Of course there is I2C, SPI, UART, and other interfaces.
