### ISSUE TITLE
mongoose iot cloud

### ISSUE THREAD

**Issue by mark-hahn** [cesanta/mongoose-iot#175]
I know this question is not a technical one for this repo, but I couldn't find a forum.  The mongoose IOT cloud looks very interesting.  It is not described in detail anywhere I can find.  Is it free?  Is the cloud-building feature a separate service than the IOT data collection and control?

**Comment by cpq** [comment]
@mark-hahn where did you look for the information?
I'd like to stick links to the forum (forum.cesanta.com) to the appropriate place.
Mongoose is free, open source, under the dual license (GPLv2 and commercial).

**Comment by mark-hahn** [comment]
I looked on every page I could find in the website.

 > Mongoose is free, open source,

I know.  I was looking for cloud information.  To repeat:

The mongoose IOT cloud  ...  Is it free? Is the cloud-building feature a separate service than the IOT data collection and control?
