### ISSUE TITLE
metrics database engine shows devices from other projects

### ISSUE THREAD

**Issue by fedy2** [cesanta/mongoose-iot#35]
I've opened the metric database panel (https://dashboard.cesanta.com/#/db) with the default project selected.
When I query for `{src=~".*"}` I get values for devices in Demo project but not in Default project:

```
[[{"__name__":"temperature","src":"//api.cesanta.com/d/fakedevice02"},[[1443628202260,19.3]]],[{"__name__":"temperature","src":"//api.cesanta.com/d/fakedevice01"},[[1443628201987,13.94]]],[{"__name__":"temperature","src":"//api.cesanta.com/d/fakedevice03"},[[1443628202572,27.03]]]]
```

**Comment by mmikulicic** [comment]
@cpq, reproduced on my account as well.

**Comment by cpq** [comment]
Closing as obsolete
