### ISSUE TITLE
ab (apache benchmark) not working on http server

### ISSUE THREAD

**Issue by alirezza** [cesanta/mongoose-iot#77]
Hi
When I ran the http server sample, It worked well in my browser,
But when I tried to get benchmark via ab,
It timed out.ab received the data,but didn't finishes.
It seems the server does not close the connection.

**Comment by mmikulicic** [comment]
yes, this has been fixed in the development head. Could you please try out the development snapshots ? You can find a link on the https://github.com/cesanta/smart.js main page.

**Comment by alashkin** [comment]
Just tried. ab works more or less good, if number of concurrent connections is not too big
