### ISSUE TITLE
Request: Exposed APIs to determine free space on file system

### ISSUE THREAD

**Issue by nkolban** [cesanta/mongoose-iot#80]
The File system allows us to read and write files but there does not yet appear to be a mechanism that would allow us to determine how much free space is available.   This request asks for consideration of a File API to determine the amount of free space available for new files.

**Comment by alashkin** [comment]
Added 'Sys.fs.free()` in https://github.com/cesanta/mongoose-iot/commit/dfb29996ece8ebb34582c693747bc9f43f91ed00

Also updated doc: https://github.com/cesanta/mongoose-iot/blob/master/docs/javascript-api/sys.md

**Comment by dvdobrovolskiy** [comment]
Not  on esp8266?
