### ISSUE TITLE
Request: Expose Sockets API

### ISSUE THREAD

**Issue by nkolban** [cesanta/mongoose-iot#83]
This request asks for exposure of raw sockets APIs both as a socket server and a socket client.  While I fully realize that we have HTTP support, I'd like to also ask for native sockets support.  Ideally, this would include both TCP and UDP flavors.

**Comment by cpq** [comment]
Neil, are you talking about something like `Net` API in nodejs , https://nodejs.org/api/net.html ?

**Comment by nkolban** [comment]
Yes ... I believe so.  Unfortunately I am not yet skilled in Node.js but a quick glance at the APIs seems to show what I would expect from a sockets implementation.

**Comment by intx82** [comment]
+1 
it would by nice use some raw network functions

**Comment by lukevenediger** [comment]
Related to #98 (UDP Support)

**Comment by alashkin** [comment]
We implemented Node-like TCP & UDP API
See here for details:
https://docs.cesanta.com/mongoose-iot/latest/#/javascript-api/udp/
https://docs.cesanta.com/mongoose-iot/latest/#/javascript-api/tcp/

Feel free to try and report bugs ;)

**Comment by dude-mansaa** [comment]
Above links of UDP and TCP apis are broke. Could you please provide the correct links?

**Comment by cpq** [comment]
https://cesanta.com/docs/overview/intro.html
